services:
  postgres:
    image: postgres:17.1
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_DEFAULT_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper

  billing-service:
    build:
      context: ./billing-service
    container_name: billing-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - kafka

  business-service:
    build:
      context: ./business-service
    container_name: business-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka

  console-service:
    build:
      context: ./console-service
    container_name: console-service
    ports:
      - "8081:8081"
    depends_on:
      - business-service

  telegram-service:
    build:
      context: ./telegram-service
    container_name: telegram-service
    ports:
      - "8082:8082"
    environment:
      TELEGRAM_BOT_TOKEN: "7650285239:AAErFmH9TqHJ_0UbpPd0MzQDBL0DjK6CxEY"
      TELEGRAM_BOT_NAME: "java_edu_project_bot"
    depends_on:
      - business-service

volumes:
  postgres_data:
